pipeline {
    agent any
    options {
        timeout(time: 20, unit: 'MINUTES')
    }
    stages {
        stage('Checkout repo') {
            steps {
                checkout scmGit(
                branches: [[name: 'master']],
                userRemoteConfigs: [[url: 'https://github.com/Hardik-Ahi/Spring-Boot_DevOps.git']]
                )
            }
        }
        stage('Build Spring project') {
            environment {
                JAVA_HOME = "/usr/lib/jvm/java-21-amazon-corretto.x86_64"
            }
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew :bootJar --info'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t spring-backend .'
                sh 'docker tag spring-backend:latest ahihardik11/spring-backend:latest'
                sh 'docker push ahihardik11/spring-backend:latest'
            }
        }
        stage('Terraform infrastructure') {
            steps {
                sh 'cd terraform && terraform init && terraform apply --auto-approve'
            }
        }
    }
}
